info:
  artifact: spring-actuator-example
  name: Spring Boot Actuator Example
  description: Spring Boot Actuator Example
  version: 1.0.0

#actuator endpoints
endpoints:
  default:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
  loggers:
    enabled: true
  #custom endpoint
  myhealth:
    enabled: true

#spring:
#  metrics:
#    web:
#      server:
#        auto-time-requests: true

spring:
  output:
    ansi:
      enabled: ALWAYS
  metrics:
    simple:
      enabled: true
    statsd:
      enabled: true
    web:
      server:
        auto-time-requests: true
#    use-global-registry: true

