info:
  artifact: spring-actuator-example
  name: Spring Boot Actuator Example
  description: Spring Boot Actuator Example
  version: 1.0.0

#Exposes Spring actuator endpoints
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: true
    details:
      enabled: true
    application:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  metrics:
    export:
      datadog:
        enabled: false


#spring:
#  metrics:
#    web:
#      server:
#        auto-time-requests: true

spring:
  output:
    ansi:
      enabled: ALWAYS
  metrics:
    simple:
      enabled: true
    statsd:
      enabled: true
    web:
      server:
        auto-time-requests: true
#    use-global-registry: true
